### ISSUE TITLE
Unauthorised / Other exceptions for Rest?

### ISSUE THREAD

**Issue by Trentan** [BorderTech/restfriends#29]
https://github.com/BorderTech/restfriends/tree/master/restfriends-envelope/src/main/java/com/github/bordertech/restfriends/exception

Currently the rest friends exceptions only cater for two specific error responses:
	@Override
	public int getStatusCode() {
		return 400;
	}

Not that there should be a specific class exception for each possible response:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

Should we implement logic to set an appropriate response code? (Or is there a better way).

Thanks

**Comment by jonathanaustin** [comment]
Hey Trentan,

As there are so many potential status codes RestFriends just went with providing the basic `400` and `500`.

If projects need more specific status codes they can implement their own Exceptions by extending `RestBusinessException` or `RestSystemException` and override `getStatusCode` to provide the required status code. They can then throw these exceptions when needed and if they are using the `RestBusinessExceptionHandler` and `RestSystemExceptionHandler` then the status codes will be automatically set.

For example, to implement `401 unauthorised`:

``` java
public class UnauthorizedException extends RestBusinessException {

	public UnauthorizedException() {
		super("Not authorized");
	}

	@Override
	public int getStatusCode() {
		return 401;
	}
}
```

If you find you are always needing a specific status code (eg 401), let us know as it would be worthwhile adding it as a predefined exception in RestFriends.

Another choice projects have is to extend or implement their own error handler to catch a certain exception and set the appropriate status code.

Hope this helps.

Jonathan

**Comment by Trentan** [comment]
Cheers yeah I did that for now, just a heads up.
